### ISSUE TITLE
Why still MVC?

### ISSUE THREAD

**Issue by aleksandrenko** [petermuessig/my-es6-ui5-app#1]
Why are you still basin` you apps architecture on the MVC pattern?
The current way of structuring the app and the data flow is much better. 
Are you considering moving to 'group by feature' file structure and to one-directional data flow like the flux paradigm?

**Comment by petermuessig** [comment]
This MVC pattern is widely used and we need to continue to support it. It is our base case. Right now we did not consider to change the file structure for the templates but it is maybe worth to think of. Regarding the unidirectional data flow this is indeed something we thought about and played around with. Unfortunately, till now nothing happened in that direction besides of experiments to use rx.js within UI5.
